Removed target Python 3.9, as it currently fails (sphinx).
UnsatisfiableError: The following specifications were found to be in conflict:
- python 3.9*
- sphinx -> docutils >=0.11 -> python 3.5* -> libffi >=3.2.1,<3.3a0
- sphinx -> docutils >=0.11 -> python 3.5* -> openssl >=1.0.2n,<1.0.3a
- sphinx -> docutils >=0.11 -> python 3.5* -> readline >=7.0,<8.0a0